package:
  name: cartopy
  version: 0.13.0

source:
  git_url: https://github.com/SciTools/cartopy.git
  git_tag: v0.13.0

  patches:
    - cartopy.win.patch  # [win]

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - six
    - numpy
    - cython
    - proj4
    # On OSX you have to pin the geos version explicitly when building alongside basemap as the conda resolver can't
     # seem to work it out correctly.
    - geos ==3.3.3
    - shapely >=1.5.6
    - owslib
    - pyshp
    - pyepsg
  
  run:
    - python
    - six
    - mock
    - nose
    - pil
    - owslib
    - numpy
    - proj4
    - shapely >=1.5.6
    - scipy
    - pyshp
    - matplotlib
    - pyepsg

test:
  imports:
    - cartopy
    - cartopy.mpl.geoaxes
    - cartopy.crs

about:
  home: http://scitools.org.uk/cartopy
  license: GNU LGPL
  summary: 'A library providing cartographic tools for python'

